// Mocks generated by Mockito 5.0.10 from annotations
// in numarketplace/test/app/features/offer/state_notifiers/purchase/purchase_state_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:numarketplace/app/features/offer/repositories/purchase_repository.dart'
    as _i3;
import 'package:numarketplace/app/shared/models/customer_model.dart' as _i5;
import 'package:numarketplace/app/shared/models/offer_model.dart' as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [PurchaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseRepository extends _i1.Mock
    implements _i3.PurchaseRepository {
  MockPurchaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<String, _i5.CustomerModel>> purchase(
          _i6.OfferModel? offer) =>
      (super.noSuchMethod(Invocation.method(#purchase, [offer]),
              returnValue: Future<_i2.Either<String, _i5.CustomerModel>>.value(
                  _FakeEither<String, _i5.CustomerModel>()))
          as _i4.Future<_i2.Either<String, _i5.CustomerModel>>);
}
